configuration:
  - debug
  - release

install:
  - set QTDIR=C:\Qt\5.6\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - mkdir build
  - cd build
  - qmake ..
  - mingw32-make

artifacts:
  - path: rtk2csv\build\RTK2CSV.exe
    name: RTK2CSV