install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
build_script:
  - qmake rtk2csv.pro CONFIG+=static
  - mingw32-make
  - mingw32-make check
  - dir /b /s *.exe
#after_build:
  #- cmd: copy README.md src\release\README.txt
  #- cmd: copy LICENSE src\release\LICENSE.txt
artifacts:
  - path: Output\rtk2csv-*.exe
  - path: src\release\rtk2csv.exe