configuration:
  - debug
  - release

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

before_build:
  - mkdir output
  - ls
  - qmake rtk2csv.pro CONFIG+=%CONFIGURATION
  - ls

build_script:
  - mingw32-make
  - mingw32-make check
  - dir /b /s *.exe

after_build:
  #- cmd: copy README.md src\release\README.txt
  #- cmd: copy LICENSE src\release\LICENSE.txt
  - pwd
  - ls
  - windeployqt --%CONFIGURATION% --compiler-runtime %CONFIGURATION%/RTK2CSV.exe
  - 7z a -tzip HORUS_RTK2CSV.zip %CONFIGURATION%/* -r
  #- copy %APPVEYOR_BUILD_FOLDER%-build\HORUS_RTK2CSV.zip %APPVEYOR_BUILD_FOLDER%\HORUS_RTK2CSV.zip
  - pwd
  - ls
  - dir /b /s *.zip

artifacts:
  - path: HORUS_RTK2CSV.zip
    name: RTK2CSV