version: '{branch}-{build}'

init:

environment:
  VSVER: 14.0 # Visual Studio 2015
  matrix:
    - QTDIR: C:\Qt\5.6\msvc2015
    - QTDIR: C:\Qt\5.6\msvc2015_64

configuration:
  - debug
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - set QTDIR
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'
  - pwd
  - ls
  - find . -type f -name '*.exe' | sed 's|.*\.||' | sort -u

artifacts:
  - path: $(configuration)\RTK2CSV.exe
    name: RTK2CSV